# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-MSWordSpell
version:      1.011
version_from: lib/Lingua/MSWordSpell.pm
installdirs:  site
requires:
    Test::More:                    0.42
    Win32::OLE:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
